name: Aws EC2
on: 
    [workflow_dispatch]
permissions: 
   id-token: write
   contents: read
jobs:
    EC2_Initialize:
        runs-on: ubuntu-latest
        steps:

            - uses: actions/checkout@v4
              
             
            - uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: "1.1.7"

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}


            - name: version check
              run: terraform version

            - name: initialize the dir
              run:  cd project && terraform init


            - name: initialize the dir
              run:  cd project && terraform plan

            - name: initialize the dir
              run: cd project && terraform apply -auto-approve
              

              

    